basePath: /
definitions:
  health.healthResponse:
    properties:
      health_check:
        type: string
    type: object
  presenter.SuccessResponse-health_healthResponse:
    properties:
      data:
        $ref: '#/definitions/health.healthResponse'
      status:
        type: integer
    type: object
host: localhost
info:
  contact: {}
  description: This is TodoAPI by golang.
  title: TodoAPI
  version: "2.0"
paths:
  /health:
    get:
      description: apiのヘルスチェックを行う。ルーティングが正常に登録されているかを確かめる。
      responses:
        "200":
          description: Health check message
          schema:
            $ref: '#/definitions/presenter.SuccessResponse-health_healthResponse'
      summary: apiのヘルスチェックを行う
swagger: "2.0"
