basePath: /
host: localhost
info:
  contact: {}
  description: This is TodoAPI by golang.
  title: TodoAPI
  version: "2.0"
paths:
  /health:
    get:
      description: apiのヘルスチェックを行う。ルーティングが正常に登録されているかを確かめる。
      responses:
        "200":
          description: Health check message
          schema:
            additionalProperties:
              type: string
            type: object
      summary: apiのヘルスチェックを行う
swagger: "2.0"
